### ISSUE TITLE
Enchancement: Make placeholder outputs customizable via config

### ISSUE THREAD

**Issue by JohOply** [axemwa/NoStrip#6]
Hi
Could you add both {status} and {astatus} to messages?
Thanks

**Comment by axemwa** [comment]
what do u mean? you should be able to already

**Comment by axemwa** [comment]
sure I'll look into it

**Comment by axemwa** [comment]
Which messages did you want them to appear in specifically as they already work in 'toggle-message'?

**Comment by JohOply** [comment]
I'm not sure to understand your question

The point of this ticket is to add {status} and {astatus} placeholder to config, to be able to modify"disable" by "désactivé" in my language for instance

**Comment by axemwa** [comment]
So you want to be able to change the placeholder itself? Or just to add language support? The placeholders already work as intended but if u want them to be changable I can look into it

**Comment by JohOply** [comment]
Currently status is "enable" and "disabled". I want to be able to translate them in another language (like any other sentence in config)

**Comment by axemwa** [comment]
Ok I'll add language support for placeholders

**Comment by axemwa** [comment]
Can u plz send me pictures of what your config looks like and what your in-game "disabled" message looks like as I haven't handled languages yet for my plugin but it shouldn't take me long to learn how.

I just wanna make sure I know how it works, did u have to change ur config messages manually or does your computer auto-translate it for you?

**Comment by JohOply** [comment]
> Can u plz send me pictures of what your config looks like and what your in-game "disabled" message looks like as I haven't handled languages yet for my plugin but it shouldn't take me long to learn how.
> 
> I just wanna make sure I know how it works, did u have to change ur config messages manually or does your computer auto-translate it for you?

Oh no! To me, auto-translate will be a waste of time! I just want to be able to change them manually. Exactly like you did it for all current messages (unknown-command, must-be-player, no-permission...)
Right now, it's just missing "status-enable" and "status-disable" which are used with placeholder {status}, depending on the situation.

**Current config**
```
allow-help-menu: true
toggle-default-on: false
notify-on-join: true
messages:
  prefix: '&8&l[&c&l⦸ &4&lNo&c&lStrip &c&l⦸&8&l]'
  unknown-command: '&cUnknown Command'
  must-be-player: '&cYou Must Be A Player To Use This Command!'
  no-permission: '&cYou do not have permission to use that command'
  no-toggle-permission: '&cPermission {permission} Required! Contact server admin!'
  no-axe-permission: '&cAxe Is Denied! Permission Required!'
  toggle-message: '&2Log Stripping {status}'
  config-reloaded: '&2Config Reloaded!'
```

Needs simply to add
```
messages:
  status-enable: '&aenable'
  status-disable: '&cdisable'
```
To be able to replace the {status} placeholder

Yet, these texts seems defined in this file, lines 81/82 & 91/92
https://github.com/axemwa/NoStrip/blob/master/src/main/java/me/shanodekono/nostrip/commands/NoStripCommand.java
______
Also, with this enhancement, I think {astatus} become useless, because everyone is able to write "on" and "off" instead of "enable" and "disable" in config.
